package macovedj:resource-map;

interface resource-map {
  resource resource-map {
    constructor();
    insert: func(name: string, job: string);
    get: func(name: string) -> option<string>;
    keys: func() -> list<string>;
  }
}

world guest {
  export resource-map;
}